### ISSUE TITLE
Ensure that installation doesn’t escalate privileges 

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson#129]
We should ensure that installing a Meson node is only done by admins on the system and only to folders that are writable by such priviledged users. Otherwise, it might be possible for a normal user to overwrite executables

**Comment by sc0Vu** [comment]
@Mikerah  How about we don't require the root authentication? IMHO, user can utilize the linux file system and setup their own privileged usage. We should make sure they won't see/read others database and private identities.

**Comment by Mikerah** [comment]
That might be a better approach actually. It enforces the principle of least authority out of the gate. We would simply need to make sure that others can see/read other parts of the databases an private identities.
