### ISSUE TITLE
Meson plugin configuration unclear

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#13]
Katzenpost can tell its plugins which command line to use. For example `/conf/katzenpost.toml`:

```yml
...
  [[Provider.CBORPluginKaetzchen]]
    Disable = false
    Capability = "eth"
    Endpoint = "+eth"
    Command = "/go/bin/Meson"
    MaxConcurrency = 1
  [[Provider.CBORPluginKaetzchen]]
    Disable = false
    Capability = "eth"
    Endpoint = "+eth"
    Command = "/go/bin/Meson"
    MaxConcurrency = 1
    [Provider.CBORPluginKaetzchen.Config]
      log_dir = "/conf/service_logs"
      log_level = "DEBUG"
      f = "/conf/currency.toml"
...
````

The problem is that the the currency plugin [proxy.go](https://github.com/hashcloak/Meson/blob/master/proxy/proxy.go#L192) is also looking for its own config file with its own parameters in `/conf/currency.toml`:

```yml
Ticker = "ETH"
RPCUser = "rpcuser"
RPCPass = "rpcpassword"
RPCURL = "http://0.0.0.0:18232"
ChainId = 4
LogDir = "/conf/service_logs"
LogLevel = "DEBUG"
```

`LogDir` and `LogLevel` in `currency.toml` and `log_dir` and `log_level` in plugin config need to be defined, when one should be enough.

Suggestion: Move these config parameters to the katzenpost config since this should be the main source of truth and pass them down to the `proxy/proxy.go` config values.

**Comment by Mikerah** [comment]
First, that portion of the Katzenpost config file has been duplicated in your OP. Maybe, that's an issue.

Second, there's a difference between `LogDir` and `LogLevel`. I think it'll be easier to narrow down problems with an appropriate logging system e.g. `DEBUG`, `INFO`, etc.

Lastly, the `currency.toml` file is a distinct configuration from the `katzenpost.toml` file. The `currency.toml` is for the exact params needed to connect to an ETH node. The `katzenpost.toml` is for configuring the katzenpost server.

**Comment by sebohe** [comment]
Ok. I understand now. The missing piece of info was that `currency.toml` is what is used to connect to the ETH node.

Thanks!
