### ISSUE TITLE
Update Meson dependencies

### ISSUE THREAD

**Issue by sc0Vu** [hashcloak/Meson#137]
Some of packages we used in package might be old, and there might be some bugs already in the newer release.
In this issue I'll list the packages we used and whether they have newer release. Also, I'll list the change they made.

# Meson dependencies

## Katzenpost
- [X] authority: v0.0.14

- [X] core: v0.0.12 => v0.0.15

- [x] registration_client: v0.0.1 => v0.0.3

## Tendermint
- [X] tendermint: v0.34.10 => v0.34.19

- [X] tm-db: v0.6.4 => v0.6.7

## Cosmos
- [X] iavl: v0.15.3 => v0.19.0

**Comment by Mikerah** [comment]
The authority, client and server dependencies for Katzenpost, aren't those the things that we ourselves now control? If it is, we should be able to update the corresponding dependencies without reliance on an external party. We should probably specify that in the issue itself
