### ISSUE TITLE
Unable to launch loacl-auth note in docker with release 0.1.0

### ISSUE THREAD

**Issue by LYC386** [hashcloak/Meson#139]
I follow the document in[ testnet/local ](https://github.com/hashcloak/Meson/blob/master/testnet/local/README.md) to set up a new local test net with docker, but get this error from local-auth containers running docker compose up

`Error: unknown command "/chain/katzenmint.toml" for "katzenmint"`

**Comment by sc0Vu** [comment]
@LYC386 was this fixed with my previous updates?
