### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson#23]
Restructure this repo so that it contains an easy way to deploy Meson and have users easily join the network

**Comment by sebohe** [comment]
Do you have any layout you have in mind?

Moving the source code into a single repo is a good idea.

 I would then just add an `ops` directory that contains the docker files and docker testnets.

**Comment by Mikerah** [comment]
Maybe something like the following:
- `testnet_config`
   - All `Dockerfile`'s related to running a testnet and connecting to a testnet
   - `README.md` (should provide overview of how to do this)
- `plugin`
   - Code related to the Meson plugin
   - `README.md`
- `README.md`
