### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#38]
For example this [one](https://github.com/hashcloak/Meson/blob/master/plugin/go.mod#L7) is not being used anywhere and has some hash conflicts not allowing go mod to download it:

```
➜ go mod download
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
        downloaded: h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
        sum.golang.org: h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
```

I also suspect that it is not using the latest katzenpost repos as dependencies similar to this issue: https://github.com/hashcloak/Meson-client/issues/10

**Comment by Mikerah** [comment]
It's safe to remove any btcdsuite depebdencies. It's a relic from the currency plugin that I forked for Meson.

**Comment by sebohe** [comment]
Resolved here: https://github.com/hashcloak/Meson/pull/39
