### ISSUE TITLE
Mitigation plan in case katzenpost master breaks

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#52]
As of https://github.com/hashcloak/Meson/commit/0118039ba81035de9039b11f4e1ee21531ec042e the Makefile is building docker images with tags that use the latest commit of the master branch of both the katzenpost/server and katzenpost/authority repos.

In the case that one of these commits breaks our build the first step should be to change the the tag variables with a working commit

Something like this:
```make
# Change this line
katzenServerTag=$(shell git ls-remote --heads $(katzenServerRepo) | grep master | cut -c1-7)
# To:
katzenServerTag=3c51956

katzenAuthTag=$(shell git ls-remote --heads https://github.com/katzenpost/authority  | grep master | cut -c1-7)
# To:
katzenAuthTag=1c00188
```

Improvements can be done to the flow of the Makefile for example creating a integration test that always runs with the latest commit and another to test only with the stable version. This will let us know when a working commit is pushed to master of the katzenpost repos.

**Comment by Mikerah** [comment]
Is this still relevant?

**Comment by sebohe** [comment]
Yes. 

To close this issue we could use the version tags of those repos, but at this point there is no `git tag` for `v0.0.8` of `katzenpost/server`. I don't know where `go modules` got `v0.0.8`: https://github.com/hashcloak/Meson/blob/master/plugin/go.mod#L7. Maybe it just ++1 on its own?

In other words. We need a `tag` that is stable. `v0.0.7` doesn't work for us due to the different [epochs](https://github.com/katzenpost/core/commit/acdd77c18f73685efa686e62cfbb3a02651394cb) values it uses

An alternatives to the tags is using the latest working commit. When katzenpost server/authority breaks our stuff we set a fixed a commit as the target (as specified in the original comment)  instead of automatically following master commits.

**Comment by sebohe** [comment]
Closing this because the way we track the version of katzen is through the environment variables:
`KATZEN_SERVER_BRANCH` and `KATZEN_AUTH_BRANCH`.
