### ISSUE TITLE
PR builds should not push to master in docker hub

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#55]
https://travis-ci.com/hashcloak/Meson/builds/141300267#L540

**Comment by sebohe** [comment]
Found the cause https://docs.travis-ci.com/user/environment-variables/#default-environment-variables:
TRAVIS_BRANCH:
    - for push builds, or builds not triggered by a pull request, this is the name of the branch.
    - for builds triggered by a pull request this is the name of the branch targeted by the pull request.
    - for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).

**Comment by Mikerah** [comment]
As this fix been applied and can we close this issue?
