### ISSUE TITLE
Add grafana to mixnet testnet

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#69]
Grafana is better than prometheus for graphing, alerting and UI. This is for the `docker swarm` metrics.

**Comment by Mikerah** [comment]
From our last standup, it seems like this is mostly done?

**Comment by sebohe** [comment]
Grafana is setup for the ethereum nodes we are running at goerli.haslcloak.com and rinkbey.hashcloak.net and it is using the geth built in data exporter: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/#monitoring

This issue was intended to add grafana to the metrics exposed by `docker swarm`. This issue has to be scoped better by specifying whether `docker swarm` metrics is good enough for this issue. I think it is because https://github.com/hashcloak/Meson/issues/70 this going to add grafana capabilities to the mixnet nodes.

**Comment by sebohe** [comment]
Closing in favor of: https://github.com/hashcloak/Meson/issues/84
