### ISSUE TITLE
Add Prometheus exporter to katzenpost/server

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#70]
After closing this issue: https://github.com/hashcloak/Meson/issues/18

I realized that we don't have any metrics capabilities in the mixnet nodes.

To add Prometheus metrics to the mixnodes we will need to fork https://github.com/katzenpost/server and add our own prometheus exporter:

- https://prometheus.io/docs/instrumenting/writing_exporters/
- https://github.com/prometheus/client_golang

**Comment by Mikerah** [comment]
Work-in-progress PR here: https://github.com/katzenpost/server/pull/139
