### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson#76]
Before making changes in order to resolve issues in other repos, we need to ensure integration tests work across repos.
This is a blocker for many issues. 

We need a flexible integration tests that checks if a transactions arrives at the nodes for the different chains that we use.

1 - This will be tests in `integration`
2 - Will check for the transaction from end to end
3 - It will need to handle tests for both Decoy and no Decoy traffic. This closes issue: https://github.com/hashcloak/Meson-client/issues/20

**Comment by sebohe** [comment]
The tests are done. This issue is going to be closed and opened in a  new issue specifying it needs to be modularized.

**Comment by sebohe** [comment]
Modularizing issue: https://github.com/hashcloak/Meson-client/issues/29
